export const actionTypes = {
  SET_USERS: "SET_USERS",
  SET_POSTS: "SET_POSTS",
  SET_COMMENTS: "SET_COMMENTS",
  SET_USER_MAP: "SET_USER_MAP",
  SET_POSTS_MAP: "SET_POSTS_MAP",
  SET_POST_COMMENTS_MAP: "SET_POST_COMMENTS_MAP",
  START_LOADER: "START_LOADER",
  STOP_LOADER: "STOP_LOADER",
};
